### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to a member function export()

### ISSUE THREAD

**Issue by mrichman** [SchumacherFM/wordpress-to-hugo-exporter#29]
Doesn't seem to work for me.

```
$  wp hugo-export

PHP Fatal error:  Uncaught Error: Call to a member function export() on null in /var/www/html/markrichman.com/wp-content/plugins/wordpress-to-hugo-exporter/hugo-export.php:530
Stack trace:
#0 [internal function]: Hugo_Export_Command->__invoke(Array, Array)
#1 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(67): call_user_func(Array, Array, Array)
#2 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#3 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php(351): call_user_func(Object(Closure), Array, Array)
#4 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(327): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#5 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(334): WP_CLI\Runner->run_command(Array, Array)
#6 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(757): WP_CLI\Runner->_run_command()
#7 phar:///usr/local/bin/wp/php/wp-cli.php(21): WP_CLI\Runner->start()
#8 phar:///usr/local/bin/wp/php/boot-phar.php(5): include('phar:///usr/loc...')
#9 /usr/lo in /var/www/html/markrichman.com/wp-content/plugins/wordpress-to-hugo-exporter/hugo-export.php on line 530
Fatal error: Uncaught Error: Call to a member function export() on null in /var/www/html/markrichman.com/wp-content/plugins/wordpress-to-hugo-exporter/hugo-export.php:530
Stack trace:
#0 [internal function]: Hugo_Export_Command->__invoke(Array, Array)
#1 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(67): call_user_func(Array, Array, Array)
#2 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#3 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php(351): call_user_func(Object(Closure), Array, Array)
#4 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(327): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#5 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(334): WP_CLI\Runner->run_command(Array, Array)
#6 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(757): WP_CLI\Runner->_run_command()
#7 phar:///usr/local/bin/wp/php/wp-cli.php(21): WP_CLI\Runner->start()
#8 phar:///usr/local/bin/wp/php/boot-phar.php(5): include('phar:///usr/loc...')
#9 /usr/lo in /var/www/html/markrichman.com/wp-content/plugins/wordpress-to-hugo-exporter/hugo-export.php on line 530
```

I also tried this:

```
$ php hugo-export-cli.php
PHP Fatal error:  Cannot redeclare get_file_description() (previously declared in /var/www/html/markrichman.com/wp-admin/includes/file.php:71) in /var/www/html/markrichman.com/wp-admin/includes/file.php on line 86
```

**Comment by mrichman** [comment]
Disregard. Had to install `mb_string`:
```
apt-get install php7.0-mbstring
```

**Comment by SchumacherFM** [comment]
Good! Please close this issue once everything is working!
